swagger:
    base-package: com.iishoni.usercenter.web
    base-path: /**
    exclude-path: /error

beetlsql:
#    sqlPath: /sql
#    dev: true
    daoSuffix: Mapper
    basePackage: com.iishoni.usercenter.mapper